# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.1.1.dev3+gb1522ab.d20230612"
__version_tuple__ = version_tuple = (0, 1, 1, "dev3", "gb1522ab.d20230612")
