name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:

  Release:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - run: npx changelogithub@0.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
